export const githubUrl = "https://github.com/KennethicEnergy"
export const country = "Philippines"
export const linkedinUrl = "https://www.linkedin.com/in/ken-buenavista-94a736144/"
export const fullName = "Kenneth Buenavista"
export const introduction = "I create beautiful websites your users will love."
export const googleDocId = "1Hhe7097d9GVNDvz5JibYl1N80DdSg7wYhvK3CIbjjr0"