export const timelineData = [
	{
		id: 1,
		title: "Internship",
		company: "98Labs Inc.",
		companyUrl: "https://98labs.com",
		date: "November 2016 - April 2017",
		description: "I was assigned to do QA tasks. This is where my journey began and where I learned HTML and CSS and JavaScript!.",
	},
	{
		id: 2,
		title: "Front-End Web Developer",
		company: "98Labs Inc.",
		companyUrl: "https://98labs.com",
		date: "December 2018 - May 2021",
		description: "This is where I started to learn how to build a websites with React and Angular.",
	},
	{
		id: 3,
		title: "Front-End Web Developer / Production Support",
		company: "Tata Consultancy Services",
		companyUrl: "https://www.tcs.com",
		date: "May 2021 - July 2022",
		description: [
      "I worked as a maintainer of the project by reviewing other developer's code and then merging it to the main branch, up until to deploying to different environments using Jenkins tied up with Husky, SonarQube, and Fortify.",
      "I was also assigned to join the Production Support Service Team and by checking and analyzing the problems raised by other Agents using New Relic, Devo and RabbitMQ",
    ],
    projectUrl: "projects/tcs",
    projectImages: [
      "/images/projects/manulife-id-1.png",
      "/images/projects/manulife-id-2.png",
      "/images/projects/manulife-id-3.png",
      "/images/projects/manulife-id-4.png",
    ],
    projectGif: "/images/project-gifs/manulife-id.gif",
    projectName: "Manulife ID",
    projectDescription: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus blanditiis ipsum mollitia reprehenderit sint neque architecto ut ratione nulla tenetur quas,
        cumque est vel impedit provident repellendus reiciendis praesentium culpa aperiam nemo! Ullam magni voluptate commodi aspernatur temporibus iure,
        culpa dolore sint quas eaque debitis itaque facilis voluptas fugiat perspiciatis!`
	},
	{
		id: 4,
		title: "Senior Front-End Web Developer",
		company: "Collabera Digital",
		companyUrl: "https://www.collaberadigital.com",
		date: "July 2022 - July 2023",
		description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    projectUrl: "projects/collabera",
    projectImages: [
      "/images/projects/cebupacific-1.png",
      "/images/projects/cebupacific-2.png",
      "/images/projects/cebupacific-3.png",
      "/images/projects/cebupacific-4.png",
    ],
    projectGif: "/images/project-gifs/cebupacific.gif",
    projectName: "Cebu Pacific Air",
    projectDescription: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus blanditiis ipsum mollitia reprehenderit sint neque architecto ut ratione nulla tenetur quas,
        cumque est vel impedit provident repellendus reiciendis praesentium culpa aperiam nemo! Ullam magni voluptate commodi aspernatur temporibus iure,
        culpa dolore sint quas eaque debitis itaque facilis voluptas fugiat perspiciatis!`
	},
	{
		id: 5,
		title: "Senior Front-End Web Developer",
		company: "W-Bridges Manpower Corporation",
		companyUrl: "https://wbridgesmanpower.com",

		date: "September 2023 - September 2024",
		description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    projectUrl: "projects/w-bridges",
    projectImages: [
      "/images/projects/game99-1.png",
      "/images/projects/game99-2.png",
      "/images/projects/game99-3.png",
      "/images/projects/game99-4.png",
      "/images/projects/game99-5.png",
      "/images/projects/game99-6.png",
      "/images/projects/game99-7.png",
    ],
    projectGif: "/images/project-gifs/game99.gif",
    projectName: "Game99",
    projectDescription: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus blanditiis ipsum mollitia reprehenderit sint neque architecto ut ratione nulla tenetur quas,
        cumque est vel impedit provident repellendus reiciendis praesentium culpa aperiam nemo! Ullam magni voluptate commodi aspernatur temporibus iure,
        culpa dolore sint quas eaque debitis itaque facilis voluptas fugiat perspiciatis!`
	},
	{
		id: 6,
		title: "Senior Front-End Web Developer",
		company: "BossDeal Corporation",
		date: "September 2024 - Present",
		description:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
	},
];
